# Generated by Django 5.0.3 on 2024-06-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_review_model_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_model',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
