# Generated by Django 5.0.3 on 2024-06-11 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_review_model_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_model',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
